openapi: 3.0.1
info:
  title: Community Connect API
tags:
  - name: channelco
    description: Public API for channelco
paths:
  /v1/onboarding/tenant:
    get:
      tags:
        - Get
        - User's
        - Pod
        - And
        - Availability
        - For
        - Onboarding
        - V1
        - Onboarding
        - Tenant
      summary: Get user's pod and availability for onboarding
  /v1/channelco/user:
    get:
      tags:
        - Search
        - Channelco
        - User
        - V1
        - Onboarding
        - Tenant
        - Channelco
        - User
      summary: Search channelco user
    post:
      tags:
        - Create
        - Channelco
        - User
        - V1
        - Onboarding
        - Tenant
        - Channelco
        - User
      summary: Create channelco user
  /v1/channelco/company/{companyId}/user/{userId}/roles/add:
    post:
      tags:
        - Adds
        - Role
        - To
        - Channelco
        - User's
        - Account
        - V1
        - Onboarding
        - Tenant
        - Channelco
        - User
        - Id
        - Roles
        - Add
      summary: Adds a role to a channelco user's account
  /v1/channelco/company/{companyId}/user/{userId}:
    get:
      tags:
        - Get
        - Channelco
        - User
        - By
        - Company
        - Id
        - And
        - V1
        - Onboarding
        - Tenant
        - Channelco
        - User
        - Id
        - Roles
        - Add
      summary: Get channelco user by companyId and userId
    put:
      tags:
        - Update
        - Channelco
        - User
        - V1
        - Onboarding
        - Tenant
        - Channelco
        - User
        - Id
        - Roles
        - Add
      summary: Update channelco user
    delete:
      tags:
        - Disable
        - Chann
        - V1
        - Onboarding
        - Tenant
        - Channelco
        - User
        - Id
        - Roles
        - Add
      summary: Disable cha
