openapi: 3.0.0
info:
  title: Symphony Profile Manager
paths:
  /v1/groups/{groupId}/member:
    post:
      summary: Add a new user to a an existing group
      description: Add a new user to a an existing group
      tags:
        - Add
        - New
        - User
        - To
        - An
        - Existing
        - Group
        - Id
        - Member
  /v1/groups:
    post:
      summary: Insert a new group
      description: Insert a new group into database
      tags:
        - Insert
        - New
        - Group
        - Id
        - Member
        - V1
        - Groups
  /v1/groups/{groupId}:
    get:
      summary: Retrieve a group
      description: Retrieve a group
      tags:
        - Retrieve
        - Group
        - Id
        - Member
        - V1
        - Groups
    put:
      summary: Update a group
      description: Update an existing group
      tags:
        - Update
        - Group
        - Id
        - Member
        - V1
        - Groups
  /v1/groups/type/{typeId}:
    get:
      summary: List all groups of specified type
      tags:
        - List
        - All
        - Groups
        - Of
        - Specified
        - Type
        - Id
        - Member
        - V1
        - Groups
  /v1/groups/{groupId}/avatar:
    post:
      summary: Update the group avatar
      description: Update the group account avatar
      tags:
        - Update
        - The
        - Group
        - Avatar
        - Id
        - Member
        - V1
        - Groups
        - Avatar
  /v1/groups/deleteAll:
    delete:
      summary: >-
        Delete all data related to the current pod (extracted from JWT). This
        endpoint is for maintenance/test and it is usually disabled or
        restricted
      tags:
        - Delete
        - All
        - Data
        - Related
        - To
        - The
        - Current
        - Pod
        - (extracted
        - From
        - T).
        - This
        - Endpoint
        - Is
        - For
        - Maintenance/test
        - And
        - It
        - Usually
        - Disabled
        - Or
        - Restricted
        - Id
        - Member
        - V1
        - Groups
        - Avatar
        - All
  /v1/types:
    get:
      summary: List all types
      tags:
        - List
        - All
        - Types
        - Id
        - Member
        - V1
        - Groups
        - Avatar
        - All
        - Types
  /v1/types/{typeId}:
    get:
      summary: Retrieve a type
      description: Retrieve a type
      tags:
        - Retrieve
        - Type
        - Id
        - Member
        - V1
        - Groups
        - Avatar
        - All
        - Typ
