openapi: 3.0.2
info:
  title: Acuris Entities API
tags:
  - name: entities
    description: Get list of entities
paths:
  /entities:
    get:
      tags:
        - Get
        - List
        - Of
        - Entities
        - (with
        - Optional
        - Filters)
        - Entities
      summary: Get list of entities (with optional filters)
      description: >-
        Returns JSON containing entities matching given filtering criteria set
        (or top ten entities when no filters are provided).
  /entities/{id}:
    get:
      tags:
        - Get
        - One
        - Entity
        - By
        - Its
        - Entities
        - Id
      summary: Get one entity by its ID
  /entities/hierarchy:
    get:
      tags:
        - Get
        - Entities
        - Hierarchy
        - (with
        - Optional
        - Filters)
        - Entities
        - Id
        - Hierarchy
      summary: Get entities hierarchy (with optional filters)
      description: >-
        Returns JSON containing entities matching given filtering criteria set
        (or top ten entities when no fi
