openapi: 3.0.1
info:
  title: AFI Optimizer API
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
paths:
  /analytics/engines/afi/v3/optimizations:
    post:
      tags:
        - Create
        - And
        - Run
        - Optimization
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
      summary: Create and Run AFI optimization
      description: "This endpoint creates and runs AFI optimization specified in the POST body parameters.\r\n            \r\nRemarks:\r\n            \r\n*\tAny settings in POST body will act as a one-time override over the settings saved in the strategy document."
  /analytics/engines/afi/v3/optimizations/{id}:
    put:
      tags:
        - Create
        - Or
        - Update
        - Optimization
        - And
        - Run
        - It.
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
        - Id
      summary: Create or Update AFI optimization and run it.
      description: >-
        This endpoint updates and run the AFI optimization specified in the PUT
        body parameters. It also allows the creation of new AFI optimization
        with custom id.
    get:
      tags:
        - Get
        - Optimization
        - Parameters
        - By
        - Id
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
        - Id
      summary: Get AFI optimization parameters by id
      description: >-
        This is the endpoint that returns the optimization parameters passed for
        an optimization.
    delete:
      tags:
        - Cancel
        - Optimization
        - By
        - Id
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
        - Id
      summary: Cancel AFI optimization by id
      description: This is the endpoint to cancel a previously submitted optimization.
  /analytics/engines/afi/v3/optimizations/{id}/status:
    get:
      tags:
        - Get
        - Optimization
        - Status
        - By
        - Id
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
        - Id
        - Status
      summary: Get AFI optimization status by id
      description: "This is the endpoint to check on the progress of a previously requested optimization.\r\nIf the optimization has finished computing, the body of the response will contain result in JSON.\r\nOtherwise, the optimization is still running and the X-FactSet-Api-PickUp-Progress header will contain a progress percentage."
  /analytics/engines/afi/v3/optimizations/{id}/result:
    get:
      tags:
        - Get
        - Optimization
        - Result
        - By
        - Id
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
        - Id
        - Status
        - Result
      summary: Get AFI optimization result by id
      description: >-
        This is the endpoint to get the result of a previously requested
        optimization.
  /analytics/engines/afi/v3/strategies/{path}:
    get:
      tags:
        - Get
        - Axioma
        - Strategy
        - Documents
        - And
        - Sub-directories
        - In
        - Directory
        - Analytics
        - Engines
        - Afi
        - V3
        - Optimizations
        - Id
        - Status
        - Result
        - Strategies
        - Path
      summary: Get Axioma FI strategy documents and sub-directories in a directory
      description: >-
        This endpoint looks up all Axioma FI strategy documents and
        sub-directories i
