openapi: 3.0.1
info:
  title: Axioma Equity API
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
paths:
  /analytics/lookups/v3/accounts/{path}:
    get:
      tags:
        - Get
        - Accounts
        - And
        - Sub-directories
        - In
        - Directory
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
      summary: Get accounts and sub-directories in a directory
      description: >-
        This endpoint looks up all ACCT and ACTM files and sub-directories in a
        given directory.
  /analytics/engines/axp/v3/optimizations:
    post:
      tags:
        - Create
        - And
        - Run
        - Axioma
        - Optimization
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
      summary: Create and Run Axioma optimization
      description: "This endpoint creates and runs Axioma optimization specified in the POST body parameters.\r\n            \r\nRemarks:\r\n            \r\n*\tAny settings in POST body will act as a one-time override over the settings saved in the strategy document."
  /analytics/engines/axp/v3/optimizations/{id}:
    put:
      tags:
        - Create
        - Or
        - Update
        - Axioma
        - Optimization
        - And
        - Run
        - It.
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
      summary: Create or Update Axioma optimization and run it.
      description: >-
        This endpoint updates and run the Axioma optimization specified in the
        PUT body parameters. It also allows the creation of new Axioma
        optimization with custom id.
    get:
      tags:
        - Get
        - Axioma
        - Optimization
        - Parameters
        - By
        - Id
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
      summary: Get Axioma optimization parameters by id
      description: >-
        This is the endpoint that returns the optimization parameters passed for
        a calculation.
    delete:
      tags:
        - Cancel
        - Axioma
        - Optimization
        - By
        - Id
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
      summary: Cancel Axioma optimization by id
      description: This is the endpoint to cancel a previously submitted optimization.
  /analytics/engines/axp/v3/optimizations/{id}/status:
    get:
      tags:
        - Get
        - Axioma
        - Optimization
        - Status
        - By
        - Id
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
        - Status
      summary: Get Axioma optimization status by id
      description: "This is the endpoint to check on the progress of a previously requested optimization.\r\nIf the optimization has finished computing, the body of the response will contain result in JSON.\r\nOtherwise, the optimization is still running and the X-FactSet-Api-PickUp-Progress header will contain a progress percentage."
  /analytics/engines/axp/v3/optimizations/{id}/result:
    get:
      tags:
        - Get
        - Axioma
        - Optimization
        - Result
        - By
        - Id
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
        - Status
        - Result
      summary: Get Axioma optimization result by id
      description: >-
        This is the endpoint to get the result of a previously requested
        optimization.
  /analytics/lookups/v3/currencies:
    get:
      tags:
        - Get
        - Currencies
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
        - Status
        - Result
        - Currencies
      summary: Get currencies
      description: >-
        This endpoint lists all the currencies that can be applied to any
        calculation.
  /analytics/engines/axp/v3/strategies/{path}:
    get:
      tags:
        - Get
        - Axioma
        - Equity
        - Strategy
        - Documents
        - And
        - Sub-directories
        - In
        - Directory
        - Analytics
        - Lookups
        - V3
        - Accounts
        - Path
        - Engines
        - Axp
        - Optimizations
        - Id
        - Status
        - Result
        - Currencies
        - Strategies
      summary: Get Axioma Equity strategy documents and sub-directories in a directory
      description: >-
        This endpoint looks up all Axioma Equity strategy documents and
        sub-directories i
