openapi: 3.0.3
info:
  title: FactSet Capital Structure Report Builder API
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: Read more about STACH 2.0's row organized schema
  url: https://factset.github.io/stachschema/#/v2/RowOrganized
tags:
  - name: Capital Structure
paths:
  /dcs-detail:
    get:
      tags:
        - Debt
        - Capital
        - Structure
        - S)
        - Dcs
        - Detail
      summary: Debt Capital Structure (DCS)
  /source-of-capital:
    get:
      tags:
        - Source
        - Of
        - Capital
        - Dcs
        - Detail
        - Source
        - Of
        - Capital
      summary: Source of Capital
  /dcs-summary:
    get:
      tags:
        - Debt
        - Capital
        - Struc
        - Dcs
        - Detail
        - Source
        - Of
        - Capital
        - Summary
      summary: Debt Capital Str
