openapi: 3.0.1
info:
  title: Chart Generation Service
paths:
  /v1/catalog/categories:
    get:
      tags:
        - Get
        - List
        - Of
        - Chart
        - Categories
        - V1
        - Catalog
        - Categories
      summary: Get a list of chart categories
  /v1/catalog/charts:
    get:
      tags:
        - Get
        - List
        - Of
        - Chart
        - Templates
        - That
        - Can
        - Be
        - Used
        - For
        - Getting
        - The
        - Image
        - From
        - Service.
        - V1
        - Catalog
        - Categories
        - Charts
      summary: >-
        Get a list of chart templates that can be used for getting the image
        from the service.
      description: >-
        You can get all the charts present or can just get the information by
        categories. The response includes the name of the chart, description,
        tags and any additional input specific to that chart. Use the
        information from this response to determine what charts you want and get
        its image from /images endpoint. Additionally you can also get back a
        auto generated PDF for the categories you requested for.
  /v1/image:
    get:
      tags:
        - Get
        - Chart
        - Image
        - Back
        - In
        - V1
        - Catalog
        - Categories
        - Charts
        - Image
      summary: Get chart image back
