openapi: 3.0.0
info:
  title: CTS Data Dictionary API
paths:
  /navigator/products:
    get:
      tags:
        - Get
        - The
        - List
        - Of
        - Products
        - For
        - Navigator.
        - Navigator
        - Products
      summary: Get the list of products for Navigator.
  /navigator/data_items/{Product_id}:
    get:
      tags:
        - Get
        - The
        - List
        - Of
        - Data
        - Items
        - Associated
        - With
        - Product
        - For
        - Navigator.
        - Navigator
        - Products
        - Product_id
      summary: Get the list of data items associated with a product for Navigator.
  /navigator/sources/{DataItem_id}:
    get:
      tags:
        - Get
        - List
        - Of
        - Sources
        - Where
        - The
        - Specified
        - Data
        - Item
        - Can
        - Be
        - Found,
        - For
        - Each
        - Delivery
        - Method,
        - Filtered
        - To
        - Appearances
        - Given
        - Within
        - Product.
        - Navigator
        - Products
        - Product_id
        - Data
        - Item_id
      summary: >-
        Get a list of sources where the specified data item can be found, for
        each delivery method, filtered to the appearances of the given data item
        within the specified product.
  /navigator/sources:
    get:
      tags:
        - Get
        - List
        - Of
        - Sources
        - By
        - Delivery
        - Method
        - For
        - The
        - Given
        - Product_id
        - Navigator
        - Products
        - Product_id
        - Data
        - Item_id
        - Sources
      summary: Get a list of sources by delivery method for the given product_id
  /navigator/table_fields/{Table_id}:
    get:
      tags:
        - Get
        - The
        - List
        - Of
        - Fields
        - Associated
        - With
        - Table
        - For
        - Navigator,
        - And
        - Code
        - Information
        - Specified
        - Data
        - Item,
        - If
        - Applicable.
        - Navigator
        - Products
        - Product_id
        - Data
        - Item_id
        - Sources
        - Table_id
      summary: >-
        Get the list of fields associated with a table for Navigator, and the
        code information for the specified data item, if applicable.
  /navigator/basic_search:
    post:
      tags:
        - Returns
        - The
        - Data
        - Items
        - (along
        - With
        - Products
        - They
        - Belong
        - To)
        - That
        - Contain
        - At
        - Least
        - One
        - Of
        - Search
        - Terms
        - As
        - Substring
        - Either
        - Their
        - Na
        - Navigator
        - Products
        - Product_id
        - Data
        - Item_id
        - Sources
        - Table_id
        - Basic_search
      summary: >-
        Returns the data items (along with the products they belong to) that
        contain at least one of the search terms as a substring of either their
