weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-tags-object-error
    message: Tag Object
  - code: openapi-openapi-version-301-info
    message: 3.0.1 Version of OpenAPI
  - code: openapi-openapi-version-310-info
    message: 3.1.0 Version of OpenAPI
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-terms-of-service-error
    message: Terms of Service
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-description-error
    message: Info Description
  - code: openapi-info-contact-info
    message: Contact Object
  - code: openapi-info-contact-url-error
    message: Contact URL
  - code: openapi-info-contact-name-info
    message: Contact Name
  - code: openapi-info-contact-email-info
    message: Contact Email
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-description-error
    message: Operation Description
  - code: openapi-operations-operation-ids-error
    message: Operation ID.
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-length-error
    message: Operation Summary Length
  - code: openapi-operations-summary-period-none-error
    message: Operation Summary Period
  - code: openapi-response-get-200-status-code-info
    message: GET Response Has 200 Status Code
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-response-get-200-content-info
    message: GET Content
  - code: openapi-response-get-200-media-type-info
    message: JSON Media Type GET
  - code: openapi-response-get-200-media-type-schema-error
    message: Schema GET
  - code: openapi-response-get-400-status-code-info
    message: 400 Status Code for GET Responses
  - code: openapi-response-get-404-status-code-info
    message: 404 Status Code for GET Responses
  - code: openapi-response-get-500-status-code-info
    message: 500 Status Code for GET Responses
  - code: openapi-security-schemes-info
    message: Security Scheme
