openapi: 3.0.1
info:
  title: DSOTM API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /transactions:
    post:
      tags:
        - Push
        - Transactions
        - Data
        - Into
        - Fact
        - Set.
        - Transactions
      summary: Push transactions data into FactSet.
      description: This endpoint takes the transactions data and pushes them into FactSet.
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/direct-streaming-tran
