openapi: 3.0.0
info:
  title: Documents Distributor - Documents API
paths:
  /global-filings/v1/list-files:
    get:
      tags:
        - Retrieve
        - Filings
        - Within
        - Fact
        - Set
        - Coverage
        - Global
        - Filings
        - V1
        - List
        - Files
      summary: Retrieve filings within FactSet coverage
      description: Parameters can be used to get the filings
  /asynch/streetaccount/v1/request-files:
    get:
      tags:
        - Returns
        - The
        - Job
        - Global
        - Filings
        - V1
        - List
        - Files
        - Asynch
        - Streetaccount
        - Request
      summary: Returns the jobID
      description: >-
        Give the startDate and endDate parameters as request parameters in the
        /request-files endpoint, it returns the jobID. startDate and endDate
        should be in YYYY-MM-DDTHH:MM:SSZ format


        This API only supports adhoc requests to retrieve historical files and
        does not support real-time       files and if you interested in require
        real-time push should consider the other three methods         (pushed
        via SFTP, to QNT account, or your Azure Storage). Per API request able
        to query till 2 years of data
  /asynch/streetaccount/v1/check-status:
    get:
      tags:
        - Returns
        - The
        - Status
        - And
        - Percent
        - Done
        - Of
        - Requested
        - Job
        - Global
        - Filings
        - V1
        - List
        - Files
        - Asynch
        - Streetaccount
        - Request
        - Check
        - Status
      summary: Returns the status and percentDone of the requested jobID
      description: >-
        Need to plug-in the jobID got from /request-files into /check-status
        endpoint
  /asynch/streetaccount/v1/get-files:
    get:
      tags:
        - Returns
        - The
        - Files
        - For
        - Specified
        - Daterange
        - Global
        - Filings
        - V1
        - List
        - Files
        - Asynch
        - Streetaccount
        - Request
        - Check
        - Status
        - Get
      summary: Returns the SA XML files for the specified daterange
      description: >-
        Need to plug-in the jobID got from /request-files into /check-status
        endpoint
  /asynch/news/v1/request-files:
    get:
      tags:
        - Returns
        - The
        - Job
        - Global
        - Filings
        - V1
        - List
        - Files
        - Asynch
        - Streetaccount
        - Request
        - Check
        - Status
        - Get
        - News
      summary: Returns the jobID
      description: >-
        Give the startDate,endDate and source parameters as request parameters
        in the /request-files endpoint, it returns the jobID. startDate and
        endDate should be in YYYY-MM-DDTHH:MM:SSZ format

        This API only supports adhoc requests to retrieve historical files
  /asynch/news/v1/check-status:
    get:
      tags:
        - Returns
        - The
        - Status
        - And
        - Percent
        - Done
        - Of
        - Requested
        - Job
        - Source
        - Global
        - Filings
        - V1
        - List
        - Files
        - Asynch
        - Streetaccount
        - Request
        - Check
        - Status
        - Get
        - News
      summary: Returns the status and percentDone of the requested jobID and source
      description: >-
        Need to plug-in the jobID got from /request-files into /check-status
        endpoint
  /asynch/news/v1/get-files:
    get:
      tags:
        - Returns
        - The
        - News
        - Filings
        - For
        - Specified
        - Daterange
        - And
        - Source
        - Global
        - Filings
        - V1
        - List
        - Files
        - Asynch
        - Streetaccount
        - Request
        - Check
        - Status
        - Get
        - News
      summary: Returns the news filings for the specified daterange and source
      description: Need to plug-in the source and jobID got from /request-files into
