openapi: 3.0.3
info:
  title: Event Calendar API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
tags:
  - name: Company
    description: Company tag
paths:
  /company/event/list:
    post:
      summary: Retrieve Company Event data
      description: This endpoint returns all company events with filters from the request.
      tags:
        - Retrieve
        - Company
        - Event
        - Data
        - Company
        - Event
        - Li
