openapi: 3.0.0
info:
  title: Exchange Snapshot API
paths:
  /v1/list-files:
    get:
      summary: Snapshot
      tags:
        - Snapshot
        - V1
        - List
        - Files
      description: >-
        A service that provides access to Real Time or Delayed data snapped at
        hourly intervals for an entire Exchange
    parameters: nu
