openapi: 3.0.0
info:
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Exchange DataFeed Snapshot
externalDocs:
  description: OpenFactSet Marketplace Card
  url: >-
    https://open.factset.com/products/factset-exchange-datafeed-snapshot-api/en-us
paths:
  /DFSnapshot:
    get:
      summary: Request a snapshot of exchange data for a list of symbols.
      tags:
        - Request
        - Snapshot
        - Of
        - Exchange
        - Data
        - For
        - List
        - Symbols.
        - Snapshot
      description: >

        `ids` and `oc` are required parameters, but only one can be used based
        on request. Use `ids` for regular snapshot requests, and `oc` for
        requesting an option chain. 


        **Try it Out** feature is available using a pre-recorded sandbox
        environment. Follow Try it Out inscrutions on each parameter to develop
        a request and view a sample server response.


        '*You must be logged into the Developer Portal and obtain an **[API
        Key](https://developer.factset.com/factset/api-key-listing)** for ''Try
        it Out'' to receive a successful server response. Select **Authorize**
        button or visit **[Authentication
        Support](https://developer.factset.com/authentication)** for more
        details.*'
    post:
      summary: Snap exchange data. Use if URL lengh of 2,048 is exceeded.
      tags:
        - Snap
        - Exchange
        - Data.
        - Use
        - If
        - Lengh
        - Of
        - 2,048
        - Is
        - Exceeded.
        - Snapshot
      description: Request Snapshot exchange data. Use POST when your URL length excee
