openapi: 3.0.1
info:
  title: FI API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /analytics/engines/fi/v3/discount-curves:
    get:
      tags:
        - Get
        - Discount
        - Curves
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
      summary: Get Discount Curves
      description: >-
        This endpoint lists all the discount curves that can be applied to a FI
        calculation.
  /analytics/engines/fi/v3/calculations:
    post:
      tags:
        - Create
        - And
        - Run
        - Calculation
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
        - Calculations
      summary: Create and Run FI calculation
      description: >-
        This endpoint creates and runs a new FI calculation specified in the
        post body.
  /analytics/engines/fi/v3/calculations/{id}:
    put:
      tags:
        - Create
        - Or
        - Update
        - Calculation
        - And
        - Run
        - It.
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
        - Calculations
        - Id
      summary: Create or Update FI calculation and run it.
      description: >-
        This endpoint updates and run the FI optimization specified in the PUT
        body parameters. It also allows the creation of new FI optimization with
        custom id.
    get:
      tags:
        - Get
        - Calculation
        - Parameters
        - By
        - Id
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
        - Calculations
        - Id
      summary: Get FI calculation parameters by id
      description: >-
        This is the endpoint that returns the calculation parameters passed for
        a calculation.
    delete:
      tags:
        - Cancel
        - Calculation
        - By
        - Id
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
        - Calculations
        - Id
      summary: Cancel FI calculation by id
      description: This is the endpoint to cancel a previously submitted calculation.
  /analytics/engines/fi/v3/calculations/{id}/status:
    get:
      tags:
        - Get
        - Calculation
        - Status
        - By
        - Id
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
        - Calculations
        - Id
        - Status
      summary: Get FI calculation status by id
      description: "This is the endpoint to check on the progress of a previously requested calculation.\r\nIf the calculation has finished computing, the body of the response will contain the requested document in JSON.\r\nOtherwise, the calculation is still running and the X-FactSet-Api-PickUp-Progress header will contain a progress percentage."
  /analytics/engines/fi/v3/calculations/{id}/result:
    get:
      tags:
        - Get
        - Calculation
        - Result
        - By
        - Id
        - Analytics
        - Engines
        - Fi
        - V3
        - Discount
        - Curves
        - Calculations
        - Id
        - Status
        - Result
      summary: Get FI calculation result by id
      description: "This is the endpoint to get the result of a previously requested calculation.\r\nIf the calculation has finished computing, the body of the response will contain the requested document in JSON."
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/fixed-in
