openapi: 3.0.1
info:
  title: FIAB API
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
paths:
  /analytics/engines/fiab/v1/calculations:
    post:
      tags:
        - Run
        - Calculation
        - Analytics
        - Engines
        - Fiab
        - V1
        - Calculations
      summary: Run FIAB calculation
      description: "This endpoint creates a new FIAB calculation.\r\nThis must be used first before get status or cancelling endpoints with a calculation id.\r\nA successful response will contain the URL to check the status of the calculation request.\r\n\r\nRemarks:\r\n*\tAny settings in POST body will act as a one-time override over the settings saved in the FIAB template."
    get:
      tags:
        - Get
        - All
        - Calculation
        - Summaries
        - Analytics
        - Engines
        - Fiab
        - V1
        - Calculations
      summary: Get all FIAB calculation summaries
      description: This endpoints returns all FIAB calculation requests.
  /analytics/engines/fiab/v1/calculations/{id}:
    get:
      tags:
        - Get
        - Calculation
        - By
        - Id
        - Analytics
        - Engines
        - Fiab
        - V1
        - Calculations
        - Id
      summary: Get FIAB calculation by id
      description: This is the endpoint to check on the progress of a previously r
