openapi: 3.0.0
info:
  title: FactSet Fundamentals API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/factset-fundamentals-api
paths:
  /fundamentals:
    get:
      tags:
        - Returns
        - Company
        - Fundamental
        - Data.
        - Fundamentals
      summary: Returns Company Fundamental Data.
      description: >
        Retrieves FactSet Fundamental standardized data for specified
        securities. Use the ```/metrics``` endpoint to retrieve a full list of
        valid metrics or data items.



        The ```/fundamentals``` endpoint currently supports Long Running
        asynchronous requests up to **20 minutes** via batch parameter. Id
        limits are increased to 2000 ids per request when using batch
        capability. This 2000 id limit has been derived based on single metric
        for one day. This feature is available for all users.       
    post:
      tags:
        - Returns
        - Company
        - Fundamental
        - Data.
        - Fundamentals
      summary: Returns Company Fundamental Data.
      description: >
        Retrieves FactSet Fundamental standardized data for specified
        securities. Use the ```/metrics``` endpoint to retrieve a full list of
        valid metrics or data items.



        The ```/fundamentals``` endpoint currently supports Long Running
        asynchronous requests up to **20 minutes** via batch parameter. Id
        limits are increased to 30000 ids per request when using batch
        capability. This 30000 id limit has been derived based on single metric
        for one day. This feature is available for all users. 
  /segments:
    get:
      tags:
        - Returns
        - Company
        - Segments
        - Data.
        - Fundamentals
        - Segments
      summary: Returns Company Segments data.
      description: >
        Retrieves Fundamentals Metrics data for individual companies.


        The ```/segments``` endpoint currently supports Long Running
        asynchronous requests up to **20 minutes** via batch parameter. Id
        limits are increased to 2000 ids per request when using batch
        capability.This 2000 id limit has been derived based on single metric
        for one day. This feature is available for all users.
    post:
      tags:
        - Returns
        - Company
        - Segment
        - Data.
        - Fundamentals
        - Segments
      summary: Returns Company Segment Data.
      description: >
        Retrieves Sales Metrics data for specified companies.


        The ```/segments``` endpoint currently supports Long Running
        asynchronous requests up to **20 minutes** via batch parameter. Id
        limits are increased to 30000 ids per request when using batch
        capability.This 30000 id limit has been derived based on single metric
        for one day. This feature is available for all users.
  /metrics:
    get:
      summary: Returns available FactSet Fundamental metrics and ratios.
      tags:
        - Returns
        - Available
        - Fact
        - Set
        - Fundamental
        - Metrics
        - And
        - Ratios.
        - Fundamentals
        - Segments
        - Metrics
      description: >
        Returns list of available FF_* metrics that can be used in the `metrics`
        parameter of related endpoints. These are related to FactSet
        Fundamentals standardized data. As Reported will be available in future
        endpoints. Leave Category and Subcategory blank to request all available
        items. The Endpoint Data model is optimized for time-series data with
        periodicity. Some items in this list are non-time series.

        **For methodology definitions, reference the `OApageID` or `OAurl`
        response items to launch the available methodology page.**
  /batch-status:
    get:
      tags:
        - Returns
        - The
        - Status
        - For
        - Batch
        - |
          Request
        - Fundamentals
        - Segments
        - Metrics
        - Batch
        - Status
      summary: |
        Returns the status for a Batch Request
      description: >-
        Return the status for the underlying batch request that is specified by
        the id.
  /batch-result:
    get:
      tags:
        - Returns
        - The
        - Response
        - For
        - Batch
        - |
          Request
        - Fundamentals
        - Segments
        - Metrics
        - Batch
        - Status
        - Result
      summary: |
        Returns the response for a Batch Request
      description: >
        Returns the response data for the underlying batch request that is
        specified by the id.


        By default, this endpoint will return data as JSON. If you wish to
        receive your data in CSV format, you can edit the header to have the
        "accept" parameter as "text/csv" instead of
