openapi: 3.0.3
info:
  title: FactSet Fundamentals Report Builder
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: Read more about STACH 2.0's row organized schema
  url: https://factset.github.io/stachschema/#/v2/RowOrganized
tags:
  - name: Financials
paths:
  /income-statement:
    get:
      tags:
        - Income
        - Statement
        - Income
        - Statement
      summary: Income Statement
      description: Returns a standardized Income Statement based on industry.
  /balance-sheet:
    get:
      tags:
        - Balance
        - Sheet
        - Income
        - Statement
        - Balance
        - Sheet
      summary: Balance Sheet
      description: Returns a standardized Balance Sheet based on industry.
  /cash-flow:
    get:
      tags:
        - Cash
        - Flow
        - Income
        - Statement
        - Balance
        - Sheet
        - Cash
        - Flow
      summary: Cash Flow
      description: Returns a standardized Cash Fl
