openapi: 3.0.3
info:
  title: Investment Banking Office Refresh API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
paths:
  /refresh/calculate:
    post:
      summary: Upload a spreadsheet file
      description: >-
        Upload a spreadsheet file (in the Open Office XML format) for FactSet to
        refresh.
      tags:
        - Upload
        - Spreadsheet
        - File
        - Refresh
        - Calculate
  /refresh/{id}/status:
    get:
      summary: Get the status of the refresh job with the given resource ID
      description: Check the status of the given job by the resource ID
      tags:
        - Get
        - The
        - Status
        - Of
        - Refresh
        - Job
        - With
        - Given
        - Resource
        - Refresh
        - Calculate
        - Id
        - Status
  /refresh/{id}:
    get:
      summary: Retrieve a calculated file by resource ID.
      description: If the requested job is complete, the calculated file will be returned.
      tags:
        - Retrieve
        - Calculated
        - File
        - By
        - Resource
        - D.
        - Refresh
        - Calculate
        - Id
        - Status
tags:
  - name: nu
