openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/contact-relationships:
    get:
      tags:
        - Get
        - All
        - The
        - Relationships
        - Where
        - Given
        - Symbol
        - Or
        - Contact
        - Identifier
        - Has
        - Been
        - Tagged
        - In
        - Relationship
        - V1
        - Contact
        - Relationships
      summary: >-
        Get all the relationships where the given symbol or contact identifier
        has been tagged in a relationship
    post:
      tags:
        - Create
        - Contact
        - Relationship
        - V1
        - Contact
        - Relationships
      summary: Create a contact relationship
  /v1/contact-relationships/{contactRelationshipId}:
    get:
      tags:
        - Get
        - Details
        - 'On'
        - Specific
        - Contact
        - Relationship
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
      summary: Get details on a specific contact relationship
    patch:
      tags:
        - Update
        - Contact
        - Relationship
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
      summary: Update a contact relationship
    delete:
      tags:
        - Delete
        - Contact
        - Relationship
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
      summary: Delete a contact relationship
  /v1/contacts:
    get:
      tags:
        - Get
        - List
        - Of
        - All
        - Contacts
        - In
        - Your
        - Group
        - Along
        - With
        - Some
        - Their
        - Standard
        - Field
        - Data
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
      summary: >-
        Get list of all contacts in your group along with some of their standard
        field data
    post:
      tags:
        - Create
        - Contact
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
      summary: Create a contact
  /v1/contacts/{contactId}:
    get:
      tags:
        - Get
        - All
        - Custom
        - Field
        - And
        - Standard
        - Details
        - 'On'
        - Specific
        - Contact
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
      summary: Get all custom field and standard field details on a specific contact
    patch:
      tags:
        - Edit
        - Contact’s
        - Standard
        - Field
        - And
        - Custom
        - Data
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
      summary: Edit a contact’s standard field and custom field data
    delete:
      tags:
        - Delete
        - Contact
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
      summary: Delete a contact
  /v1/contacts/{contactId}/about:
    get:
      tags:
        - Get
        - The
        - About
        - Field
        - Content
        - For
        - Specific
        - Contact
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
        - About
      summary: Get the About field content for a specific contact
  /v1/contacts/{contactId}/events:
    get:
      tags:
        - Get
        - Contact’s
        - Audit
        - History
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
        - About
        - Events
      summary: Get a contact’s audit history
  /v1/contacts/{contactId}/records:
    get:
      tags:
        - Get
        - All
        - Notes
        - And
        - Meetings
        - Where
        - Specific
        - Contact
        - Was
        - Tagged
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
        - About
        - Events
        - Records
      summary: Get all notes and meetings where a specific contact was tagged
  /v1/contacts/{contactId}/relationships:
    get:
      tags:
        - Returns
        - List
        - Of
        - Contact’s
        - Relationships
        - V1
        - Contact
        - Relationships
        - Relationship
        - Id
        - Contacts
        - About
        - Events
        - Records
      summary: Returns a list of a contact’s relationships
tags:
  - name: Contacts
  - name: Cont
