openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/custom-symbols:
    get:
      tags:
        - Get
        - List
        - Of
        - All
        - Custom
        - Symbols
        - In
        - Your
        - Group
        - Along
        - With
        - Some
        - Their
        - Standard
        - Field
        - And
        - Fields
        - Data
        - V1
        - Custom
        - Symbols
      summary: >-
        Get list of all custom symbols in your group along with some of their
        standard field and custom fields data
    post:
      tags:
        - Create
        - Custom
        - Symbol
        - V1
        - Custom
        - Symbols
      summary: Create a custom symbol
  /v1/custom-symbols/{customSymbolId}:
    get:
      tags:
        - Get
        - All
        - Custom
        - Field
        - And
        - Standard
        - Details
        - 'On'
        - Specific
        - Symbol
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
      summary: >-
        Get all custom field and standard field details on a specific custom
        symbol
    patch:
      tags:
        - Edit
        - Custom
        - Symbol’s
        - Standard
        - Field
        - And
        - Data
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
      summary: Edit a custom symbol’s standard field and custom field data
    delete:
      tags:
        - Delete
        - Custom
        - Symbol
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
      summary: Delete a custom symbol
  /v1/custom-symbols/{customSymbolId}/records:
    get:
      tags:
        - Get
        - All
        - Notes
        - And
        - Meetings
        - Where
        - Specific
        - Custom
        - Symbol
        - Was
        - Tagged
        - As
        - Primary
        - Or
        - Related
        - Identifier
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
      summary: >-
        Get all notes and meetings where a specific customSymbol was tagged as
        primary or related identifier
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbol}:
    get:
      tags:
        - Get
        - All
        - Custom
        - Field
        - And
        - Standard
        - Details
        - 'On'
        - Specific
        - Symbol
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
      summary: >-
        Get all custom field and standard field details on a specific standard
        symbol
  /v1/symbol-relationships/{symbolId}/relationships:
    get:
      tags:
        - Returns
        - List
        - Of
        - Symbol’s
        - Relationships
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
      summary: Returns a list of a symbol’s relationships
  /v1/symbol-relationships/{symbolRelationshipId}:
    get:
      tags:
        - Get
        - Details
        - 'On'
        - Specific
        - Symbol
        - Relationship
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
      summary: Get details on a specific symbol relationship
    delete:
      tags:
        - Delete
        - Symbol
        - Relationship
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
      summary: Delete a symbol relationship
  /v1/custom-symbols/{customSymbolId}/link-standard-symbol:
    post:
      tags:
        - Link
        - Custom
        - Symbol
        - To
        - Standard
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
        - Link
        - Standard
      summary: Link custom symbol to standard symbol
  /v1/custom-symbols/standard-symbol-metadata:
    post:
      tags:
        - Create
        - Standard
        - Symbol
        - Metadata
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
        - Link
        - Standard
        - Metadata
      summary: Create standard symbol metadata
  /v1/symbol-relationships:
    post:
      tags:
        - Create
        - Symbol
        - Relationship
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
        - Link
        - Standard
        - Metadata
      summary: Create a symbol relationship
  /v1/symbol-relationships/{symbol}:
    put:
      tags:
        - Edit
        - Symbol
        - Relationship
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
        - Link
        - Standard
        - Metadata
      summary: Edit a symbol relationship
  /v1/custom-symbols/standard-symbol-metadata/{standardSymbolId}:
    patch:
      tags:
        - Edit
        - Standard
        - Symbol’s
        - Field
        - And
        - Custom
        - Data
        - V1
        - Custom
        - Symbols
        - Symbol
        - Id
        - Records
        - Relationships
        - Relationship
        - Link
        - Standard
        - Metadata
      summary: Edit a standard symbol’s standard field and custom field data
tags:
  - name: CustomSymbols
  - name: CustomSymbols - Relationships
  - name: nu
