openapi: 3.0.1
info:
  title: IRN API v1
paths:
  /v1/meetings:
    get:
      tags:
        - Get
        - All
        - The
        - Meetings
        - In
        - Specified
        - Date
        - Range
        - Filtered
        - 'On'
        - Given
        - Identifiers
        - V1
        - Meetings
      summary: >-
        Get all the meetings in the specified date range filtered on the given
        identifiers
    post:
      tags:
        - Create
        - Meeting
        - V1
        - Meetings
      summary: Create a meeting
  /v1/meetings/{meetingId}:
    get:
      tags:
        - Get
        - Details
        - Of
        - Meeting
        - V1
        - Meetings
        - Id
      summary: Get details of a meeting
    put:
      tags:
        - Update
        - Meeting
        - V1
        - Meetings
        - Id
      summary: Update meeting
    delete:
      tags:
        - Delete
        - Meeting
        - V1
        - Meetings
        - Id
      summary: Delete a Meeting
  /v1/meetings/{meetingId}/attachments:
    get:
      tags:
        - Get
        - All
        - The
        - Attachments
        - Belonging
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
      summary: Get all the attachments belonging to a meeting
    post:
      tags:
        - Create
        - An
        - Attachment
        - For
        - Existing
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
      summary: Create an attachment for a existing meeting
  /v1/meetings/{meetingId}/attachments/{attachmentId}/download:
    get:
      tags:
        - Download
        - An
        - Attachment
        - From
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
      summary: Download an attachment from a Meeting
  /v1/meetings/{meetingId}/comments:
    get:
      tags:
        - Get
        - All
        - Comments
        - For
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
      summary: Get all comments for a meeting
    post:
      tags:
        - Create
        - Comment
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
      summary: Create a comment to a Meeting
  /v1/meetings/{meetingId}/comments/{commentId}:
    get:
      tags:
        - Get
        - Details
        - Of
        - Comment
        - Belonging
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
      summary: Get details of a comment belonging to a meeting
    patch:
      tags:
        - Edit
        - Comment
        - For
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
      summary: Edit a comment for a meeting
    delete:
      tags:
        - Delete
        - Comment
        - From
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
      summary: Delete a Comment from a Meeting
  /v1/meetings/{meetingId}/comments/{commentId}/attachments:
    get:
      tags:
        - Get
        - Attachments
        - Summary
        - Of
        - Comment
        - Belonging
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
      summary: Get attachments summary of a comment belonging to a meeting
    post:
      tags:
        - Create
        - Comment
        - Attachment
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
      summary: Create a comment attachment to a Meeting
  /v1/meetings/{meetingId}/comments/{commentId}/attachments/{attachmentId}/download:
    get:
      tags:
        - Download
        - Single
        - Attachment
        - Detail
        - Of
        - Comment
        - Belonging
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
      summary: Download single attachment detail of a comment belonging to a meeting
  /v1/meetings/{meetingId}/events:
    get:
      tags:
        - Get
        - All
        - The
        - Record
        - Events
        - That
        - Belong
        - To
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
        - Events
      summary: Get all the record events that belong to a meeting
  /v1/meetings/{meetingId}/events/{recordEventId}:
    get:
      tags:
        - Get
        - Details
        - Of
        - Record
        - Event
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
        - Events
        - Record
        - Event
      summary: Get details of a record event of a meeting
  /v1/meetings/{meetingId}/attachments/{attachmentId}:
    delete:
      tags:
        - Delete
        - Attachment
        - From
        - Meeting
        - V1
        - Meetings
        - Id
        - Attachments
        - Attachment
        - Download
        - Comments
        - Comment
        - Events
        - Record
        - Event
      summary: Delete attachment from meeting
tags:
  - name: Attachments
  - name: Comments
  - name: Events
  - name: null
