openapi: 3.0.3
info:
  title: Portfolio Metadata
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /account-composite:
    post:
      description: Create a new account composite
      tags:
        - Account
        - Composite
    get:
      description: List account composite
      tags:
        - Account
        - Composite
  /account-composite/{id}:
    delete:
      description: Remove a account composite
      tags:
        - Account
        - Composite
        - Id
    get:
      description: Read a account composite
      tags:
        - Account
        - Composite
        - Id
    put:
      description: Modify a account composite
      tags:
        - Account
        - Composite
        - Id
  /account:
    post:
      description: Create a new account
      tags:
        - Account
        - Composite
        - Id
    get:
      description: List account
      tags:
        - Account
        - Composite
        - Id
  /account/{id}:
    delete:
      description: Remove a account
      tags:
        - Account
        - Composite
        - Id
    get:
      description: Read a account
      tags:
        - Account
        - Composite
        - Id
    put:
      description: Modify a account
      tags:
        - Account
        - Composite
        - Id
  /holdings-composite/{id}:
    get:
      description: Read a holdings composite
      tags:
        - Account
        - Composite
        - Id
        - Holdings
  /holdings/{id}:
    get:
      description: Read a holdings
      tags:
        - Account
        - Composite
        - Id
        - Holdings
  /returns-composite/{id}:
    get:
      description: Read a returns composite
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
  /returns/{id}:
    get:
      description: Read a returns
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
  /trade-data/{id}:
    get:
      description: Read a trade data
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
        - Trade
        - Data
  /user-defined-field-group:
    get:
      description: List user defined groups
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
        - Trade
        - Data
        - User
        - Defined
        - Field
        - Group
  /user-defined-field-group/{id}:
    get:
      description: Read a specific user defined field group and list its fields.
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
        - Trade
        - Data
        - User
        - Defined
        - Field
        - Group
  /user-defined-field:
    get:
      description: List user defined fields
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
        - Trade
        - Data
        - User
        - Defined
        - Field
        - Group
  /user-defined-field/{id}:
    get:
      description: Read a user defined field
      tags:
        - Account
        - Composite
        - Id
        - Holdings
        - Returns
        - Trade
        - Data
        - User
        - Defined
        - Field
        - Group
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/portfolio-metadata-api
tags:
  - name: Account
    description: CRUD operations on Account
  - name: Account Composite
    description: CRUD operations on Account Composite
  - name: Holdings
    description: CRUD operations on Holdings
  - name: Holdings Composite
    description: CRUD operations on Holdings Composite
  - name: Returns
    description: CRUD operations on Returns
  - name: Returns Composite
    description: CRUD operations on Returns Composite
  - name: Trade Data
    description: CRUD operations on Trade Data
  - name: User Defined Field
    description: CRUD operations on User Defined Field
  - name: User Defined Field Group
    description: CRUD operations on User
