openapi: 3.0.1
info:
  title: ModelAccounts API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /analytics/accounts/v3/models/{name}:
    put:
      tags:
        - Create
        - Or
        - Update
        - An
        - Existing
        - Model
        - Account
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
      summary: Create or update an existing model account
    delete:
      tags:
        - Delete
        - Model
        - Account,
        - Takes
        - An
        - Account
        - Path
        - And
        - Name
        - Deletes
        - It.
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
      summary: Delete model account, takes an account path and name and deletes it.
    get:
      tags:
        - Get
        - Account
        - Endpoint,
        - Takes
        - An
        - Name
        - And
        - Returns
        - Underlying
        - Data
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
      summary: Get account endpoint, takes an account name and returns underlying data
  /analytics/accounts/v3/models/{name}/symbols/{symbol}:
    delete:
      tags:
        - Delete
        - All
        - Entries
        - For
        - Symbol
        - Or
        - Specific
        - Date
        - From
        - Previously
        - Created
        - Account.
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
        - Symbols
        - Symbol
      summary: >-
        Delete all entries for a symbol or specific date entries for a symbol
        from a previously created account.
    get:
      tags:
        - Get
        - Account
        - Endpoint,
        - Takes
        - An
        - Name,
        - Symbol
        - And
        - Returns
        - Underlying
        - Data
        - For
        - That
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
        - Symbols
        - Symbol
      summary: >-
        Get account endpoint, takes an account name, symbol and returns
        underlying data for that symbol
  /analytics/accounts/v3/models/{name}/dates/{date}:
    delete:
      tags:
        - Delete
        - All
        - Entries
        - For
        - Date
        - Or
        - Specific
        - Symbol
        - From
        - Previously
        - Created
        - Account.
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
        - Symbols
        - Symbol
        - Dates
        - Date
      summary: >-
        Delete all entries for a date or specific symbol entries for a date from
        a previously created account.
    get:
      tags:
        - Get
        - Account
        - Endpoint,
        - Takes
        - An
        - Name,
        - Date
        - And
        - Returns
        - Underlying
        - Data
        - For
        - That
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
        - Symbols
        - Symbol
        - Dates
        - Date
      summary: >-
        Get account endpoint, takes an account name, date and returns underlying
        data for that date
  /analytics/accounts/v3/models/{name}/dates/{date}/symbols/{symbol}:
    get:
      tags:
        - Get
        - Account
        - Endpoint,
        - Takes
        - An
        - Name
        - And
        - Returns
        - Underlying
        - Data
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
        - Symbols
        - Symbol
        - Dates
        - Date
      summary: Get account endpoint, takes an account name and returns underlying data
  /analytics/accounts/v3/models/{name}/schema:
    get:
      tags:
        - Get
        - Account
        - Schema
        - Endpoint,
        - Takes
        - An
        - Name
        - And
        - Returns
        - Its
        - Analytics
        - Accounts
        - V3
        - Models
        - Name
        - Symbols
        - Symbol
        - Dates
        - Date
        - Schema
      summary: >-
        Get account schema endpoint, takes an account name and returns its
        schema
externalDocs:
  description: API Documentation
  url: https://developer.fact
