openapi: 3.0.0
info:
  title: FactSet Private Markets API
tags:
  - name: Financials
    description: Retrieve Private Company Financials
  - name: Non-Periodic
    description: Retrieve Private Company Reference Data.
  - name: Data Items
    description: Retrieve available Private Company fields, metrics, and ratios.
paths:
  /factset-private-markets/v1/financials:
    get:
      summary: Returns Private Company Financials for a list of ids.
      description: |
        Returns Private Company Financials Information.
      tags:
        - Returns
        - Private
        - Company
        - Financials
        - For
        - List
        - Of
        - Ids.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
    post:
      summary: Returns Private Company Financials for a list of ids.
      description: |
        Returns a private markets financials object for the requested ids.
      tags:
        - Returns
        - Private
        - Company
        - Financials
        - For
        - List
        - Of
        - Ids.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
  /factset-private-markets/v1/non-periodic:
    get:
      summary: Returns Private Company reference data for a list of ids.
      description: |
        Returns Private Company reference information.
      tags:
        - Returns
        - Private
        - Company
        - Reference
        - Data
        - For
        - List
        - Of
        - Ids.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
        - Non
        - Periodic
    post:
      summary: Returns Private Company reference data for a list of ids.
      description: |
        Returns a private markets reference object for the requested ids.
      tags:
        - Returns
        - Private
        - Company
        - Reference
        - Data
        - For
        - List
        - Of
        - Ids.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
        - Non
        - Periodic
  /factset-private-markets/v1/fields:
    get:
      summary: Available private company fields, metrics, and ratios.
      tags:
        - Available
        - Private
        - Company
        - Fields,
        - Metrics,
        - And
        - Ratios.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
        - Non
        - Periodic
        - Fields
      description: >
        Returns list of available Private Company fields that can be used in the
        `fields` parameter of related endpoints. These are related to FactSet
        Private Company standardized data.
  /factset-private-markets/v1/universe:
    get:
      summary: Get Entity Candidates and Matches for a single name and attributes.
      description: >
        Finds the best candidate entities matching the given entity name.
        Country code can also be supplied to narrow the search. <p>**Max of 1
        Name permitted in a single GET request.** Use the POST method for
        /entity-match to fetch up to 25 names.</p><p>
      tags:
        - Get
        - Entity
        - Candidates
        - And
        - Matches
        - For
        - Single
        - Name
        - Attributes.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
        - Non
        - Periodic
        - Fields
        - Universe
    post:
      summary: >-
        Get a list of Entity Candidates and Matches for a requested list of up
        to 25 names and attributes.
      description: >
        Finds the best candidate entities matching the given entity name.
        Country code can also be supplied to narrow the search. Finds the best
        candidate entities matching the given company name. <p>**Max of 25 Names
        inputted.**</p><p>
      tags:
        - Get
        - List
        - Of
        - Entity
        - Candidates
        - And
        - Matches
        - For
        - Requested
        - Up
        - To
        - '25'
        - Names
        - Attributes.
        - Factset
        - Private
        - Markets
        - V1
        - Financials
        - Non
        - Periodic
        - Fields
        - Univer
