openapi: 3.0.0
info:
  title: FactSet SCIM API
paths:
  /ServiceProviderConfig:
    get:
      tags:
        - Get
        - Server
        - Configuration.
        - Service
        - Provider
        - Config
      summary: Get server configuration.
  /Schemas:
    get:
      tags:
        - Get
        - List
        - Of
        - Schemas.
        - Service
        - Provider
        - Config
        - Schemas
      summary: Get a list of schemas.
  /Schemas/{id}:
    get:
      tags:
        - Get
        - Schema.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
      summary: Get a schema.
  /Users:
    get:
      tags:
        - Get
        - List
        - Of
        - Users.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
      summary: Get a list of users.
    post:
      tags:
        - Create
        - User.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
      summary: Create a user.
  /Users/{id}:
    get:
      tags:
        - Get
        - User.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
      summary: Get a user.
    put:
      tags:
        - Replace
        - User.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
      summary: Replace a user.
    patch:
      tags:
        - Patch
        - User
        - (add,
        - Replace,
        - Or
        - Remove
        - Attributes
        - Of
        - User.)
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
      summary: Patch a user (add, replace, or remove attributes of a user.)
    delete:
      tags:
        - Delete
        - User
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
      summary: Delete a user
  /Groups:
    get:
      tags:
        - Get
        - List
        - Of
        - Groups.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
      summary: Get a list of groups.
  /Group/{id}:
    get:
      tags:
        - Get
        - Group.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
      summary: Get a group.
    put:
      tags:
        - Replace
        - Group.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
      summary: Replace a group.
    patch:
      tags:
        - Patch
        - Group
        - (add,
        - Replace,
        - Or
        - Remove
        - Attributes
        - Of
        - Group.)
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
      summary: Patch a group (add, replace, or remove attributes of a group.)
  /Locations:
    get:
      tags:
        - Get
        - List
        - Of
        - Locations.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
      summary: Get a list of locations.
  /Locations/{id}:
    get:
      tags:
        - Get
        - Location.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
      summary: Get a location.
    put:
      tags:
        - Replace
        - Location.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
      summary: Replace a location.
    patch:
      tags:
        - Patch
        - Location
        - (add,
        - Replace,
        - Or
        - Remove
        - Attributes
        - Of
        - Location.)
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
      summary: Patch a location (add, replace, or remove attributes of a location.)
  /Products:
    get:
      tags:
        - Get
        - List
        - Of
        - Products.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
        - Products
      summary: Get a list of products.
  /Products/{id}:
    get:
      tags:
        - Get
        - Product.
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
        - Products
      summary: Get a product.
  /FileManagerAudit:
    get:
      tags:
        - Get
        - File
        - Service
        - Provider
        - Config
        - Schemas
        - Id
        - Users
        - Groups
        - Group
        - Locations
        - Products
        - File
        - Manager
        - Audit
      summary: Get File
