openapi: 3.0.0
info:
  title: FPE API
paths:
  /analytics/quant/fpe/v1/calculations:
    post:
      tags:
        - Starts
        - New
        - Script
        - Calculation
        - Analytics
        - Quant
        - Fpe
        - V1
        - Calculations
      summary: Starts a new script calculation
      description: This endpoint takes a python script and starts executing it within FPE
  /analytics/quant/fpe/v1/calculations/{id}:
    get:
      tags:
        - Get
        - Calculation
        - Status
        - By
        - Id
        - Analytics
        - Quant
        - Fpe
        - V1
        - Calculations
        - Id
      summary: Get calculation status by id
      description: >-
        This is the endpoint to check on the progress of a previous calculation
        request.
  /analytics/quant/fpe/v1/calculations/{id}/output:
    get:
      tags:
        - Get
        - Calculation
        - Output
        - For
        - Specific
        - Analytics
        - Quant
        - Fpe
        - V1
        - Calculations
        - Id
        - Output
      summary: Get calculation output for a specific calculation
      description: This endpoint returns the specified output from the calculation.
  /analytics/quant/fpe/v1/calculations/{id}/log:
    get:
      tags:
        - Get
        - Calculation
        - Log
        - For
        - Specific
        - Analytics
        - Quant
        - Fpe
        - V1
        - Calculations
        - Id
        - Output
        - Log
      summary: Get calculation log for a specific calculation
      description: This endpoint returns the log from the calculation.
  /analytics/quant/fpe/v1/files/{server}/{file}:
    post:
      tags:
        - Starts
        - File
        - Upload
        - Analytics
        - Quant
        - Fpe
        - V1
        - Calculations
        - Id
        - Output
        - Log
        - Files
        - Server
        - File
      summary: Starts a file upload
      description: This endpoint takes a file and uploads it
  /analytics/quant/fpe/v1/files/uploads/{id}:
    get:
      tags:
        - Get
        - Upload
        - Status
        - By
        - Id
        - Analytics
        - Quant
        - Fpe
        - V1
        - Calculations
        - Id
        - Output
        - Log
        - Files
        - Server
        - File
        - Uploads
      summary: Get upload status by id
      description: This is the endpoint to check on the progress of a pr
