openapi: 3.0.0
info:
  title: News API For Digital Portals
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /news/article/get:
    get:
      tags:
        - Details
        - For
        - News
        - Article.
        - News
        - Article
        - Get
      summary: Details for a news article.
      description: Details for a news article.
  /news/article/list:
    post:
      tags:
        - List
        - Of
        - News
        - Articles.
        - News
        - Article
        - Get
        - List
      summary: List of news articles.
      description: List of news articles.
  /news/article/listByChain:
    post:
      tags:
        - List
        - News
        - Articles
        - Of
        - An
        - Article
        - Chain.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
      summary: List news articles of an article chain.
      description: List news articles of an article chain.
  /news/article/listByIndex:
    post:
      tags:
        - News
        - Articles
        - For
        - Instruments
        - That
        - Are
        - Constituents
        - Of
        - The
        - Given
        - Indices.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
      summary: >-
        News articles for instruments that are constituents of the given
        indices.
      description: >-
        News articles for instruments that are constituents of the given
        indices.
  /news/article/listByInstrument:
    post:
      tags:
        - News
        - Articles
        - For
        - Instruments.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
      summary: News articles for instruments.
      description: News articles for instruments.
  /news/article/listByMediaKind:
    post:
      tags:
        - List
        - News
        - Articles
        - Which
        - Contain
        - Media
        - Of
        - Specific
        - Kinds.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
      summary: List news articles which contain media of specific media kinds.
      description: List news articles which contain media of specific media kinds.
  /news/article/searchByText:
    post:
      tags:
        - Search
        - For
        - News
        - Articles
        - Using
        - Fulltext
        - Search.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
      summary: Search for news articles using a fulltext search.
      description: >-
        Search for news articles using a fulltext search. All specified criteria
        need to be fulfilled for an article to match. Each criterion is handled
        according to its selectionType; "include" requires the criterion to
        evaluate to true, "exclude" requires the criterion to evaluate to false.
        A criterion is fulfilled when at least one of its values is found.
  /news/article/type/get:
    get:
      tags:
        - Details
        - For
        - News
        - Article
        - Type.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
      summary: Details for a news article type.
      description: Details for a news article type.
  /news/article/type/list:
    get:
      tags:
        - List
        - Of
        - News
        - Article
        - Types.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
      summary: List of news article types.
      description: List of news article types.
  /news/distributor/get:
    get:
      tags:
        - Details
        - Of
        - Distributor.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
        - Distributor
      summary: Details of a distributor.
      description: Details of a distributor.
  /news/distributor/list:
    get:
      tags:
        - List
        - Of
        - Distributors.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
        - Distributor
      summary: List of distributors.
      description: List of distributors.
  /news/publisher/get:
    get:
      tags:
        - Details
        - Of
        - Publisher.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
        - Distributor
        - Publisher
      summary: Details of a publisher.
      description: Details of a publisher.
  /news/publisher/list:
    get:
      tags:
        - List
        - Of
        - Publishers.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
        - Distributor
        - Publisher
      summary: List of publishers.
      description: List of publishers.
  /news/publisher/listByDistributor:
    get:
      tags:
        - List
        - Of
        - Publishers
        - Provided
        - By
        - The
        - Given
        - Distributor.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
        - Distributor
        - Publisher
      summary: List of publishers provided by the given distributor.
      description: List of publishers provided by the given distributor.
  /news/publisher/searchByName:
    post:
      tags:
        - Search
        - For
        - Publishers.
        - News
        - Article
        - Get
        - List
        - By
        - Chain
        - Index
        - Instrument
        - Media
        - Kind
        - Text
        - Type
        - Distributor
        - Publisher
        - Name
      summary: Search for publishers.
      description: Search for publishers by the name of the publisher.
tags:
  - name: news
    description: news endpoints
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
x-interface-version: 2
x-documenter-version: 6.3.9
x-api-version: null
