openapi: 3.0.0
info:
  title: Price Alerting API For Digital Portals
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /alerting/prices/basic/alert/get:
    get:
      tags:
        - Details
        - Of
        - An
        - Alert.
        - Alerting
        - Prices
        - Basic
        - Alert
        - Get
      description: >-
        Details of an alert. The details include the trigger definition at the
        time of alert creation.
      summary: Details of an alert.
  /alerting/prices/basic/alert/list:
    get:
      tags:
        - List
        - Of
        - Alerts.
        - Alerting
        - Prices
        - Basic
        - Alert
        - Get
        - List
      description: List of alerts in descending order of creation.
      summary: List of alerts.
  /alerting/prices/basic/trigger/get:
    get:
      tags:
        - Details
        - Of
        - Trigger.
        - Alerting
        - Prices
        - Basic
        - Alert
        - Get
        - List
        - Trigger
      description: Details of a trigger.
      summary: Details of a trigger.
  /alerting/prices/basic/trigger/list:
    post:
      tags:
        - List
        - Of
        - Triggers.
        - Alerting
        - Prices
        - Basic
        - Alert
        - Get
        - List
        - Trigger
      description: Returns a list of triggers sorted in descending order of creation.
      summary: List of triggers.
tags:
  - name: alerting
    description: alerting endpoints
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/
x-interface-version: 2
x-documenter-version: 6.3.9
x-api-version: null
