openapi: 3.0.0
info:
  title: S&P Global Fixed Income Evaluated Prices & Analytics API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
externalDocs:
  description: API Documentation
  url: >-
    https://developer.factset.com/api-catalog/sp-global-fixed-income-evaluated-prices-and-analytics-api
paths:
  /markit-bond-prices-and-analytics/v1/prices:
    get:
      tags:
        - Get
        - Bid,
        - Mid
        - And
        - Ask
        - Prices
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
      summary: Get Bid, Mid and Ask prices for a list of securities
      description: >
        Get bond clean and dirty bid, mid and ask pricing data provided by
        Markit for a specified date range and frequency.
    post:
      tags:
        - Request
        - Bid,
        - Mid
        - And
        - Ask
        - Prices
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
      summary: Request Bid, Mid and Ask prices for a list of securities
      description: >
        Get bond clean and dirty bid, mid and ask pricing data provided by
        Markit for a specified date range and frequency.
  /markit-bond-prices-and-analytics/v1/spread:
    get:
      tags:
        - Get
        - The
        - Spread
        - And
        - Data
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
      summary: Get the Spread and OAS data for a list of securities
      description: >
        Get spread details like discount margin, OAS, Asset Swap Spread, Z
        Spread, spread benchmark provided by Markit for a specified date range
        and frequency.
    post:
      tags:
        - Request
        - The
        - Spread
        - And
        - Data
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
      summary: Request the Spread and OAS data for a list of securities
      description: >
        Get spread details like discount margin, OAS, Asset Swap Spread, Z
        Spread, spread benchmark provided by Markit for a specified date range
        and frequency.
  /markit-bond-prices-and-analytics/v1/yield:
    get:
      tags:
        - Get
        - Yield
        - Information
        - For
        - Given
        - Date
        - Range
        - And
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
      summary: Get yield information for given date range and list of securities
      description: >
        Get the yield information like yield to maturity, yield to worst,
        benchmark yield to maturity and yield to call provided by Markit for a
        specified date range and frequency. 
    post:
      tags:
        - Request
        - Yield
        - Information
        - For
        - Given
        - Date
        - Range
        - And
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
      summary: Request yield information for given date range and list of securities
      description: >
        Get the yield information like yield to maturity, yield to worst,
        benchmark yield to maturity and yield to call provided by Markit for a
        specified date range and frequency.
  /markit-bond-prices-and-analytics/v1/issuer-yield-curve:
    get:
      tags:
        - Get
        - Yield
        - Curve
        - Data
        - For
        - Given
        - Date
        - Range
        - And
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
      summary: Get yield curve data for given date range and list of securities
      description: >
        Get yield curve data points and dates for 3M, 6M, 1Y, 2Y, 3Y, 4Y, 5Y,
        6Y, 7Y, 8Y, 9Y, 10Y, 15Y, 20Y, 25Y, 30Y and 40Y provided by Markit for
        the specified date range and frequency.
    post:
      tags:
        - Request
        - Yield
        - Curve
        - Data
        - For
        - Given
        - Date
        - Range
        - And
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
      summary: Request yield curve data for given date range and list of securities
      description: >
        Get yield curve data points and dates for 3M, 6M, 1Y, 2Y, 3Y, 4Y, 5Y,
        6Y, 7Y, 8Y, 9Y, 10Y, 15Y, 20Y, 25Y, 30Y and 40Y provided by Markit for
        the specified date range and frequency.
  /markit-bond-prices-and-analytics/v1/sensitivity:
    get:
      tags:
        - Get
        - The
        - Bond
        - Sensitivity
        - Data
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
      summary: Get the bond sensitivity data for a list of securities
      description: >
        Get the sensitivity information like convexity, effective convexity,
        effective duration, Macaulay duration and modified duration provided by
        Markit for the specified date range and frequency.
    post:
      tags:
        - Request
        - The
        - Bond
        - Sensitivity
        - Data
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
      summary: Request the bond sensitivity data for a list of securities
      description: >
        Get the sensitivity information like convexity, effective convexity,
        effective duration, Macaulay duration and modified duration provided by
        Markit for the specified date range and frequency.
  /markit-bond-prices-and-analytics/v1/meta:
    get:
      tags:
        - Get
        - Bond
        - Meta
        - Data
        - For
        - List
        - Of
        - Securities.
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
        - Meta
      summary: Get bond meta data for a list of securities.
      description: >
        Get bond metadata like classification, maturity date, symbology
        information like isin, cusip, vendorid, ticker, issue and issuer name
        provided by Markit for a list of securities.
    post:
      tags:
        - Get
        - Bond
        - Meta
        - Data
        - For
        - List
        - Of
        - Securities.
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
        - Meta
      summary: Get bond meta data for a list of securities.
      description: >
        Get bond metadata like classification, maturity date, symbology
        information like isin, cusip, vendorid, ticker, issue and issuer name
        provided by Markit for a list of securities.
  /markit-bond-prices-and-analytics/v1/abs-details:
    get:
      tags:
        - Get
        - Asset
        - Backed
        - Security
        - Details
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
        - Meta
        - Abs
        - Details
      summary: Get Asset Backed Security Details for a list of securities
      description: >
        Get details for Asset Backed Securities like factors, pay up, wal, cdr,
        cpr and prepay details provided by Markit for the specified date range
        and frequency.
    post:
      tags:
        - Request
        - Asset
        - Backed
        - Security
        - Details
        - For
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
        - Meta
        - Abs
        - Details
      summary: Request Asset Backed Security Details for a list of securities
      description: >
        Get details for Asset Backed Securities like factors, pay up, wal, cdr,
        cpr and prepay details provided by Markit for the specified date range
        and frequency.
  /markit-bond-prices-and-analytics/v1/coupon:
    get:
      tags:
        - Get
        - Coupon
        - Data
        - For
        - Given
        - Date
        - Range
        - And
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
        - Meta
        - Abs
        - Details
        - Coupon
      summary: Get coupon data for given date range and list of securities
      description: >
        Get coupon information like accrued interest, coupon, coupon type and
        coupon frequency provided by Markit for specified date range and
        frequency.
    post:
      tags:
        - Request
        - Coupon
        - Data
        - For
        - Given
        - Date
        - Range
        - And
        - List
        - Of
        - Securities
        - Markit
        - Bond
        - Prices
        - And
        - Analytics
        - V1
        - Spread
        - Yield
        - Issuer
        - Curve
        - Sensitivity
        - Meta
        - Abs
        - Details
        - Coupon
      summary: Request coupon data for given date range and list of securities
      description: >
        Get coupon information like accrued interest, coupon, coupon type and
        coupon frequency provided by Markit for specified date ra
