openapi: 3.0.2
info:
  title: FactSet Search Answers API
paths:
  /search/answers/v1/data:
    get:
      summary: Fetch FactSet answer in data format
      tags:
        - Fetch
        - Fact
        - Set
        - Answer
        - In
        - Data
        - Format
        - Search
        - Answers
        - V1
        - Data
      description: >-
        Returns an answer to the specified query (if a valid answer exists).
        Returns the answer data only (as JSON), without any markup information.
  /search/answers/v1/adaptive-card:
    get:
      summary: Fetch FactSet answer in Adaptive Card format
      tags:
        - Fetch
        - Fact
        - Set
        - Answer
        - In
        - Adaptive
        - Card
        - Format
        - Search
        - Answers
        - V1
        - Data
        - Adaptive
        - Card
      description: >-
        Returns an answer to the specified query (if valid answer exists) in the
        Adaptive Card format (https://a
