openapi: 3.0.1
info:
  title: Security-Modeling API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /analytics/security-modeling/v3/securities/retrieve:
    post:
      tags:
        - Get
        - Existing
        - Securities
        - Analytics
        - Security
        - Modeling
        - V3
        - Securities
        - Retrieve
      summary: Get existing securities
      description: This endpoint gets all existing securities.
  /analytics/security-modeling/v3/securities/upsert:
    post:
      tags:
        - Create
        - Or
        - Update
        - Securities
        - Analytics
        - Security
        - Modeling
        - V3
        - Securities
        - Retrieve
        - Upsert
      summary: Create or update securities
      description: This endpoint is to create or update existing securities.
  /analytics/security-modeling/v3/securities/delete:
    post:
      tags:
        - Delete
        - Existing
        - Securities
        - Analytics
        - Security
        - Modeling
        - V3
        - Securities
        - Retrieve
        - Upsert
        - Delete
      summary: Delete existing securities
      description: This endpoint deletes existing securities.
externalDocs:
  description: API Documentation
  url: https://developer.factse
