openapi: 3.0.2
info:
  title: Signals API
tags:
  - name: Events
    description: >-
      Fetch signal events. Please note that FactSet Cognitive signals and
      signals contributed by third parties are excluded from the response for
      limited API access.
  - name: Metadata
    description: Fetch signal metadata
paths:
  /events/headlines:
    get:
      tags:
        - Events
        - Headlines
      description: >-
        Fetch Signals event headlines based on at least one of the following
        filtering parameters: `ids`, `portfolios`
    post:
      tags:
        - Events
        - Headlines
      description: >-
        Fetch Signals event headlines based on the filtering criteria for up to
        1000 identifiers and at least one of the following filtering parameters:
        `ids`, `portfolios`
  /events/details:
    get:
      tags:
        - Events
        - Headlines
        - Details
      description: >-
        Fetch Signals event headlines plus all additional event details based on
        at least one of the following filtering parameters: `ids`, `portfolios`
    post:
      tags:
        - Events
        - Headlines
        - Details
      description: >-
        Fetch Signals event headlines plus all additional event details for up
        to 1000 identifiers and at least one of the following filtering
        parameters: `ids`, `portfolios`
  /events/details/{eventId}:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
      description: >-
        Fetch Signals event headlines plus all additional event details for a
        single requested Signal event
  /events/adaptive-cards:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
      description: >-
        Fetch Microsoft's Adaptive Cards, which includes headlines and event
        details data plus hyperlinks to FactSet reports, based on at least one
        of the following filtering parameters: `ids`, `portfolios`
    post:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
      description: >-
        Fetch Microsoft's Adaptive Cards, which includes headlines and event
        details data plus hyperlinks to FactSet reports, based on at least one
        of the following filtering parameters: `ids`, `portfolios`
  /events/adaptive-cards/{eventId}:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
      description: >-
        Fetch Microsoft's Adaptive Cards, which includes headlines and event
        details data plus hyperlinks to FactSet reports, for a single requested
        Signal event
  /events/entities:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
        - Entities
      description: Fetch FactSet entity IDs for events that match the filtering criteria
    post:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
        - Entities
      description: Fetch FactSet entity IDs for events that match the filtering criteria
  /data-dictionary:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
        - Entities
        - Data
        - Dictionary
      description: Fetch a list of all active signals
  /data-dictionary/{signalId}:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
        - Entities
        - Data
        - Dictionary
      description: Fetch the metadata and contract for the requested signal
  /themes:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
        - Entities
        - Data
        - Dictionary
        - Themes
      description: Fetch a list of available signal themes
  /categories:
    get:
      tags:
        - Events
        - Headlines
        - Details
        - Id
        - Adaptive
        - Cards
        - Entities
        - Data
        - Dictionary
        - Themes
        - Categories
      description: Fetch a list of availab
