openapi: 3.0.0
info:
  title: SDF Download API
paths:
  /list-schemas:
    get:
      summary: schemas
      tags:
        - Schemas
        - List
        - Schemas
      description: >-
        <a
        href=https://api.factset.com/bulk-documents/sdf/v1/list-schemas>List-Schemas</a>
        helper end point provides the list of schemas subscribed by the client
        and their corresponding sequences if no query parameters are passed in
        the request.

         If schema & sequence number (version number of schema) are passed in the request, this endpoint provides a downloadable presigned url containing the schema information.
  /list-files:
    get:
      tags:
        - List
        - Schemas
        - Files
      description: >
        <a
        href=https://api.factset.com/bulk-documents/sdf/v1/list-files>List-Files</a>
        end point provides the delta & full files in a reverse chronological
        order by default for all the schemas & bundles subscribed by the client


         QFL:-
           - In case of QFL, <a href=https://api.factset.com/bulk-documents/sdf/v1/list-files>List-Files</a> end point provides the "Historical & Year to Date (YTD)" data in a reverse chronological order by default for all the factor families & groups subscribed to by the user</p> Provides "full files" only for historical bundles[data available from 1995 to previous year], "full & delta files" for YTD bundles[data available for current year]
           
           If startDate and endDate parameters are not specified in the request, this endpoint returns past 10 days data by default.
tags:
  - name: Schema
  - name: SDF and Q
