openapi: 3.0.3
info:
  title: StreetAccount News API
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Filters
    description: Get flattened or structured filters
  - name: Headlines
    description: Get headlines for a specified view or specified filters
  - name: Views
    description: Create, edit and delete views
  - name: StreetAccount Historical Stories
    description: Request, check the status and download the XML files.
paths:
  /streetaccount/headlines:
    post:
      summary: Retrieve StreetAccount headlines for given filters
      description: >-
        This endpoint will pull all headlines produced by StreetAccount and the
        full story body will be returned by the data set. Filters can be
        specified via the endpoint below.
      tags:
        - Retrieve
        - Street
        - Account
        - Headlines
        - For
        - Given
        - Filters
        - Streetaccount
        - Headlines
  /streetaccount/views/{id}/headlines:
    post:
      summary: Retrieve StreetAccount headlines for given view
      description: >-
        This endpoint allows you to pull all headlines produced by StreetAccount
        for a saved view. The full story body will be returned by the data set.
        Views can be created via the ‘Create Views’ endpoint.
      tags:
        - Retrieve
        - Street
        - Account
        - Headlines
        - For
        - Given
        - View
        - Streetaccount
        - Headlines
        - Views
        - Id
  /streetaccount/views:
    get:
      summary: Retrieves StreetAccount search views
      description: >-
        This endpoint allows you to pull the full list of StreetAccount views
        that have been previously saved.
      tags:
        - Retrieves
        - Street
        - Account
        - Search
        - Views
        - Streetaccount
        - Headlines
        - Views
        - Id
  /streetaccount/views/{id}:
    post:
      summary: Creates and saves a StreetAccount view
      description: >-
        This endpoint allows you to create a new StreetAccount view. Select
        watchlists/tickers and filters of your choice to create and save a view.
      tags:
        - Creates
        - And
        - Saves
        - Street
        - Account
        - View
        - Streetaccount
        - Headlines
        - Views
        - Id
    put:
      summary: Edits and saves an existing StreetAccount view
      description: >-
        This endpoint allows you to edit the criteria used for a previously
        saved StreetAccount view.
      tags:
        - Edits
        - And
        - Saves
        - An
        - Existing
        - Street
        - Account
        - View
        - Streetaccount
        - Headlines
        - Views
        - Id
    delete:
      summary: Deletes an existing StreetAccount view
      description: >-
        This endpoint allows you to delete a previously saved StreetAccount
        view.
      tags:
        - Deletes
        - An
        - Existing
        - Street
        - Account
        - View
        - Streetaccount
        - Headlines
        - Views
        - Id
  /streetaccount/filters:
    get:
      summary: Retrieve all StreetAccount filters
      tags:
        - Retrieve
        - All
        - Street
        - Account
        - Filters
        - Streetaccount
        - Headlines
        - Views
        - Id
        - Filters
      description: >-
        Add StreetAccount filters (watchlists, company filters, market topics,
        regions and sectors) to filter down StreetAccount headlines by the
        relevant categories. Set the structured and/or flattened flag. If
        structured flag is set, parent and child filter information will be
        returned. If flattened flag is set, flattened filters will be returned
        which can be used with the headlines and createView endpoints. Both
        flags can be set to return both sets of filters.  If no params are
        provided it will return both
  /streetaccount/historical/request-files:
    get:
      tags:
        - Returns
        - The
        - Job
        - Streetaccount
        - Headlines
        - Views
        - Id
        - Filters
        - Historical
        - Request
        - Files
      summary: Returns the jobID
      description: >-
        Give the startDate and endDate parameters as request parameters in the
        /request-files endpoint, it returns the jobID. startDate and endDate
        should be in YYYY-MM-DDTHH:MM:SSZ format. This API only supports adhoc
        requests to retrieve historical files and does not support real-time
        files and if you interested in require real-time push should consider
        the other three methods (pushed via SFTP, to QNT account, or your Azure
        Storage). Per API request able to query till 2 years of data
  /streetaccount/historical/check-status:
    get:
      tags:
        - Returns
        - The
        - Status
        - And
        - Percentage
        - Of
        - Completion
        - For
        - Requested
        - Job
        - Streetaccount
        - Headlines
        - Views
        - Id
        - Filters
        - Historical
        - Request
        - Files
        - Check
        - Status
      summary: Returns the status and percentage of completion for the requested jobID
      description: >-
        Need to plug-in the jobID from /request-files into /check-status
        endpoint
  /streetaccount/historical/get-files:
    get:
      tags:
        - Returns
        - The
        - Street
        - Account
        - Files
        - For
        - Specified
        - Date
        - Range
        - Streetaccount
        - Headlines
        - Views
        - Id
        - Filters
        - Historical
        - Request
        - Files
        - Check
        - Status
        - Get
      summary: Returns the StreetAccount XML files for the specified date range
      description: Need to plug-in the jobID from /check-status into /get-files endpoint
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/stre
